# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: "Publish to NPM"

on:
  push:
    branches: 
      - master

jobs:
  release:
    name: "Publish to NPM"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
            node-version: 12
            registry-url: https://registry.npmjs.org
      - id: check
        uses: EndBug/version-check@v1
        with:
            file-url: https://unpkg.com/your-package@latest/package.json
            static-checking: localIsNew
      - run: npm install
      - name: build
        run: npm run build
      - name: publish
        run: npm publish
        env:
            NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}


