
name: "Publish to NPM"

on:
  push:
    branches: 
      - master

jobs:
  release:
    name: "Publish to NPM"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
            node-version: 14
            registry-url: https://registry.npmjs.org
      - id: check
        uses: EndBug/version-check@v1
        with:
            file-url: https://unpkg.com/daisyui@latest/package.json
            static-checking: localIsNew

      - name: Install dependencies
        run: npm install

      - name: build
        run: npm run build

      - name: Publish
        run: npm publish
        if: steps.check.outputs.changed == 'true'
        env:
            NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Wait 60 seconds for npm publish
        uses: whatnick/wait-action@master
        with:
          time: '60s'

      - name: Install dependencies
        run: cd src/docs && npm install
        if: steps.check.outputs.changed == 'true'

      - name: Generate
        run: cd src/docs && npm run deploy
        if: steps.check.outputs.changed == 'true'

      - name: Deploy docs to github pages
        uses: peaceiris/actions-gh-pages@v3
        if: steps.check.outputs.changed == 'true'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./src/docs/dist
          cname: daisyui.com